/*
 * @Descripttion: 
 * @version: 
 * @Author: Eugene
 * @Date: 2023-11-23 14:44:41
 * @LastEditors: Andy
 * @LastEditTime: 2023-11-23 14:44:42
 */
/*
 * @Descripttion: 
 * @version: 
 * @Author: Eugene
 * @Date: 2023-11-20 19:36:06
 * @LastEditors: Andy
 * @LastEditTime: 2023-11-21 10:37:44
 */
// myModule.js
class MyModule {
    constructor() {
      this.prop1 = 'value1';
      this.prop2 = 'value2';
      this.prop3 = 'value3';
      this.options = [{
        value: '30',
        label: '飞行高度',
        unit: '米'
      }, {
        value: null,
        label: '飞行速度',
        unit: '米/秒'
      }, {
        value: null,
        label: '海拔高度',
        unit: null
      }, {
        value: null,
        label: '飞行模式',
        unit: null
      }, {
        value: 11,
        label: '飞行时长',
        unit: null
      }, {
        value: null,
        label: '剩余电量'
      }, {
        value: null,
        label: '通讯质量',
        unit: null
      }];
      /** 航点管理 按钮事件*/
      this.defaultClickTools={
        importWaypoints: { text: "导入航点", icon: "el-icon-plus", action: this.importWaypoints },
        addRoutes: {text: "航线规划",icon: "el-icon-plus",action: this.addRoutes},
        multiMachineImport: { text: "多机导入", icon: "el-icon-plus", action: this.multiMachineImport },
        loadingStatus: { text: "载仓状态", icon: "el-icon-plus", action: this.loadingStatus }
      };
      this.uavs=[
        {
            "uavSellByUser": "21312",
            "uavMaxspeed": 32,
            "uavProductByUser": "213",
            "playUrl1": "www.efuav.ltd/live/1002-stream1?txSecret=016f1146510fb959880930c518089392&txTime=655f10b3",
            "uavProductDate": 1686240000000,
            "uavDefaultHiveId": "1004",
            "efFactory": null,
            "uavSellDate": 1686326399000,
            "uavTypeId": 1019,
            "streamType": "webrtc",
            "efUavType": null,
            "uavStatus": 0,
            "uavName": "10022无人机",
            "limitOfCompany": 0,
            "online": false,
            "uavId": "1002",
            "uavFactoryId": 2,
            "limitOfUser": 0,
            "uavContractNo": null,
            "uavEnduranceTime": 23,
            "uavMaxpayload": 213,
            "uavWheelbase": 12,
            "selected": false,
            "isOnline": false,
            "isCharging": false,
            "isChargingText": "未知",
            "isDjiServerOnline": false,
            "isGcsOnline": false,
            "isUavOnline": false,
            "isRomoteControlOnline": false,
            "isAirLinkOnline": false,
            "isCameraOnline": false,
            "djiServerBootTime": 0,
            "djiServerTime": 0,
            "heartbeatData": null,
            "heartbeatDataTime": 0
        },
        {
            "uavSellByUser": "2",
            "uavMaxspeed": 2,
            "uavProductByUser": "2",
            "playUrl1": "www.efuav.ltd/live/1581F5FJB229Q00A01GS-stream1?txSecret=4f9790bbc14c49eaa5d310d4931a5fd3&txTime=655f10b3",
            "uavProductDate": 1689696000000,
            "uavDefaultHiveId": null,
            "efFactory": null,
            "uavSellDate": 1725033599000,
            "uavTypeId": 1017,
            "streamType": "webrtc",
            "efUavType": null,
            "uavStatus": 0,
            "uavName": "MTT3",
            "limitOfCompany": 0,
            "online": false,
            "uavId": "1581F5FJB229Q00A01GS",
            "uavFactoryId": 1,
            "limitOfUser": 0,
            "uavContractNo": null,
            "uavEnduranceTime": 2,
            "uavMaxpayload": 2,
            "uavWheelbase": 2,
            "selected": false,
            "isOnline": false,
            "isCharging": false,
            "isChargingText": "未知",
            "isDjiServerOnline": false,
            "isGcsOnline": false,
            "isUavOnline": false,
            "isRomoteControlOnline": false,
            "isAirLinkOnline": false,
            "isCameraOnline": false,
            "djiServerBootTime": 0,
            "djiServerTime": 0,
            "heartbeatData": null,
            "heartbeatDataTime": 0
        },
        {
            "uavSellByUser": "1",
            "uavMaxspeed": 1,
            "uavProductByUser": "1",
            "playUrl1": "www.efuav.ltd/live/1ZNBJ5F00C008L-stream1?txSecret=20e6a6a2e71afe9d6f1c005ee14d5c44&txTime=655f10b3",
            "uavProductDate": 1690992000000,
            "uavDefaultHiveId": null,
            "efFactory": null,
            "uavSellDate": 1691078399000,
            "uavTypeId": 1012,
            "streamType": "webrtc",
            "efUavType": null,
            "uavStatus": 0,
            "uavName": "M300",
            "limitOfCompany": 0,
            "online": false,
            "uavId": "1ZNBJ5F00C008L",
            "uavFactoryId": 1,
            "limitOfUser": 0,
            "uavContractNo": null,
            "uavEnduranceTime": 1,
            "uavMaxpayload": 1,
            "uavWheelbase": 1,
            "selected": false,
            "isOnline": false,
            "isCharging": false,
            "isChargingText": "未知",
            "isDjiServerOnline": false,
            "isGcsOnline": false,
            "isUavOnline": false,
            "isRomoteControlOnline": false,
            "isAirLinkOnline": false,
            "isCameraOnline": false,
            "djiServerBootTime": 0,
            "djiServerTime": 0,
            "heartbeatData": null,
            "heartbeatDataTime": 0
        },
        {
            "uavSellByUser": "efadmin1",
            "uavMaxspeed": 11,
            "uavProductByUser": "efadmin1",
            "playUrl1": "www.efuav.ltd/live/1000123-stream1?txSecret=3064a9420336ad739615ad880656f642&txTime=655f10b3",
            "uavProductDate": 1686585600000,
            "uavDefaultHiveId": null,
            "efFactory": null,
            "uavSellDate": 1686671999000,
            "uavTypeId": 1013,
            "streamType": "webrtc",
            "efUavType": null,
            "uavStatus": 0,
            "uavName": "管理测试无人机001",
            "limitOfCompany": 0,
            "online": false,
            "uavId": "1000123",
            "uavFactoryId": 1,
            "limitOfUser": 0,
            "uavContractNo": null,
            "uavEnduranceTime": 11,
            "uavMaxpayload": 1,
            "uavWheelbase": 11,
            "selected": true,
            "isOnline": false,
            "isCharging": false,
            "isChargingText": "未知",
            "isDjiServerOnline": false,
            "isGcsOnline": false,
            "isUavOnline": false,
            "isRomoteControlOnline": false,
            "isAirLinkOnline": false,
            "isCameraOnline": false,
            "djiServerBootTime": 0,
            "djiServerTime": 0,
            "heartbeatData": null,
            "heartbeatDataTime": 0
        },
        {
            "uavSellByUser": "4",
            "uavMaxspeed": 4,
            "uavProductByUser": "4",
            "playUrl1": "www.efuav.ltd/live/100024-stream1?txSecret=156e9d7b6932a679102f0e5baf71ce63&txTime=655f10b3",
            "uavProductDate": 1686585600000,
            "uavDefaultHiveId": "10456",
            "efFactory": null,
            "uavSellDate": 1686671999000,
            "uavTypeId": 1013,
            "streamType": "webrtc",
            "efUavType": null,
            "uavStatus": 0,
            "uavName": "管理测试11",
            "limitOfCompany": 0,
            "online": false,
            "uavId": "100024",
            "uavFactoryId": 1,
            "limitOfUser": 0,
            "uavContractNo": null,
            "uavEnduranceTime": 4,
            "uavMaxpayload": 4,
            "uavWheelbase": 4,
            "selected": false,
            "isOnline": false,
            "isCharging": false,
            "isChargingText": "未知",
            "isDjiServerOnline": false,
            "isGcsOnline": false,
            "isUavOnline": false,
            "isRomoteControlOnline": false,
            "isAirLinkOnline": false,
            "isCameraOnline": false,
            "djiServerBootTime": 0,
            "djiServerTime": 0,
            "heartbeatData": null,
            "heartbeatDataTime": 0
        },
        {
            "uavSellByUser": "lie",
            "uavMaxspeed": 1,
            "uavProductByUser": "lie",
            "playUrl1": "www.efuav.ltd/live/1001-stream1?txSecret=efa3fc3105de51ee65b1d199e3335eff&txTime=655f10b3",
            "uavProductDate": 1686153600000,
            "uavDefaultHiveId": "10456",
            "efFactory": null,
            "uavSellDate": 1686239999000,
            "uavTypeId": 1012,
            "streamType": "webrtc",
            "efUavType": null,
            "uavStatus": 0,
            "uavName": "测试无人机1001",
            "limitOfCompany": 0,
            "online": false,
            "uavId": "1001",
            "uavFactoryId": 1,
            "limitOfUser": 0,
            "uavContractNo": null,
            "uavEnduranceTime": 1,
            "uavMaxpayload": 1,
            "uavWheelbase": 1,
            "selected": false,
            "isOnline": false,
            "isCharging": false,
            "isChargingText": "未知",
            "isDjiServerOnline": false,
            "isGcsOnline": false,
            "isUavOnline": false,
            "isRomoteControlOnline": false,
            "isAirLinkOnline": false,
            "isCameraOnline": false,
            "djiServerBootTime": 0,
            "djiServerTime": 0,
            "heartbeatData": null,
            "heartbeatDataTime": 0
        },
        {
            "uavSellByUser": "1",
            "uavMaxspeed": 1,
            "uavProductByUser": "1",
            "playUrl1": "www.efuav.ltd/live/10022-stream1?txSecret=d21ef83593035eed774df7a0f7e64b85&txTime=655f10b3",
            "uavProductDate": 1686585600000,
            "uavDefaultHiveId": null,
            "efFactory": null,
            "uavSellDate": 1686671999000,
            "uavTypeId": 1,
            "streamType": "webrtc",
            "efUavType": null,
            "uavStatus": 0,
            "uavName": "管理测试无人机01",
            "limitOfCompany": 0,
            "online": false,
            "uavId": "10022",
            "uavFactoryId": 2,
            "limitOfUser": 0,
            "uavContractNo": null,
            "uavEnduranceTime": 1,
            "uavMaxpayload": 1,
            "uavWheelbase": 1,
            "selected": false,
            "isOnline": false,
            "isCharging": false,
            "isChargingText": "未知",
            "isDjiServerOnline": false,
            "isGcsOnline": false,
            "isUavOnline": false,
            "isRomoteControlOnline": false,
            "isAirLinkOnline": false,
            "isCameraOnline": false,
            "djiServerBootTime": 0,
            "djiServerTime": 0,
            "heartbeatData": null,
            "heartbeatDataTime": 0
        },
        {
            "uavSellByUser": "user02",
            "uavMaxspeed": 4,
            "uavProductByUser": "user02",
            "playUrl1": "www.efuav.ltd/live/10023-stream1?txSecret=b2d674aef70b80bfb77fbf2806e49d4d&txTime=655f10b3",
            "uavProductDate": 1686499200000,
            "uavDefaultHiveId": null,
            "efFactory": null,
            "uavSellDate": 1686585599000,
            "uavTypeId": 1,
            "streamType": "webrtc",
            "efUavType": null,
            "uavStatus": 0,
            "uavName": "测试无人机1003",
            "limitOfCompany": 0,
            "online": false,
            "uavId": "10023",
            "uavFactoryId": 2,
            "limitOfUser": 0,
            "uavContractNo": null,
            "uavEnduranceTime": 4,
            "uavMaxpayload": 4,
            "uavWheelbase": 4,
            "selected": false,
            "isOnline": false,
            "isCharging": false,
            "isChargingText": "未知",
            "isDjiServerOnline": false,
            "isGcsOnline": false,
            "isUavOnline": false,
            "isRomoteControlOnline": false,
            "isAirLinkOnline": false,
            "isCameraOnline": false,
            "djiServerBootTime": 0,
            "djiServerTime": 0,
            "heartbeatData": null,
            "heartbeatDataTime": 0
        },
        {
            "uavSellByUser": "user01",
            "uavMaxspeed": 4,
            "uavProductByUser": "user03",
            "playUrl1": "www.efuav.ltd/live/10032-stream1?txSecret=7c993a769c26cb16da6f436efb760c6d&txTime=655f10b3",
            "uavProductDate": 1686499200000,
            "uavDefaultHiveId": "1003",
            "efFactory": null,
            "uavSellDate": 1686585599000,
            "uavTypeId": 1014,
            "streamType": "webrtc",
            "efUavType": null,
            "uavStatus": 0,
            "uavName": "测试无人机1023",
            "limitOfCompany": 0,
            "online": false,
            "uavId": "10032",
            "uavFactoryId": 1,
            "limitOfUser": 0,
            "uavContractNo": null,
            "uavEnduranceTime": 4,
            "uavMaxpayload": 4,
            "uavWheelbase": 4,
            "selected": false,
            "isOnline": false,
            "isCharging": false,
            "isChargingText": "未知",
            "isDjiServerOnline": false,
            "isGcsOnline": false,
            "isUavOnline": false,
            "isRomoteControlOnline": false,
            "isAirLinkOnline": false,
            "isCameraOnline": false,
            "djiServerBootTime": 0,
            "djiServerTime": 0,
            "heartbeatData": null,
            "heartbeatDataTime": 0
        },
        {
            "uavSellByUser": "1",
            "uavMaxspeed": 1,
            "uavProductByUser": "1",
            "playUrl1": "www.efuav.ltd/live/10033-stream1?txSecret=09ab2c78fecf6163acb1578fb453e0f1&txTime=655f10b3",
            "uavProductDate": 1686585600000,
            "uavDefaultHiveId": null,
            "efFactory": null,
            "uavSellDate": 1686671999000,
            "uavTypeId": 1019,
            "streamType": "webrtc",
            "efUavType": null,
            "uavStatus": 0,
            "uavName": "管理测试无人机02",
            "limitOfCompany": 0,
            "online": false,
            "uavId": "10033",
            "uavFactoryId": 2,
            "limitOfUser": 0,
            "uavContractNo": null,
            "uavEnduranceTime": 1,
            "uavMaxpayload": 1,
            "uavWheelbase": 1,
            "selected": false,
            "isOnline": false,
            "isCharging": false,
            "isChargingText": "未知",
            "isDjiServerOnline": false,
            "isGcsOnline": false,
            "isUavOnline": false,
            "isRomoteControlOnline": false,
            "isAirLinkOnline": false,
            "isCameraOnline": false,
            "djiServerBootTime": 0,
            "djiServerTime": 0,
            "heartbeatData": null,
            "heartbeatDataTime": 0
        },
        {
            "uavSellByUser": "4",
            "uavMaxspeed": 4,
            "uavProductByUser": "4",
            "playUrl1": "www.efuav.ltd/live/10044-stream1?txSecret=13cbcf1ff2d750cf9c1814ee252a7952&txTime=655f10b4",
            "uavProductDate": 1686585600000,
            "uavDefaultHiveId": null,
            "efFactory": null,
            "uavSellDate": 1686671999000,
            "uavTypeId": 1012,
            "streamType": "webrtc",
            "efUavType": null,
            "uavStatus": 0,
            "uavName": "管理测试无人机04",
            "limitOfCompany": 0,
            "online": false,
            "uavId": "10044",
            "uavFactoryId": 1,
            "limitOfUser": 0,
            "uavContractNo": null,
            "uavEnduranceTime": 4,
            "uavMaxpayload": 4,
            "uavWheelbase": 4,
            "selected": false,
            "isOnline": false,
            "isCharging": false,
            "isChargingText": "未知",
            "isDjiServerOnline": false,
            "isGcsOnline": false,
            "isUavOnline": false,
            "isRomoteControlOnline": false,
            "isAirLinkOnline": false,
            "isCameraOnline": false,
            "djiServerBootTime": 0,
            "djiServerTime": 0,
            "heartbeatData": null,
            "heartbeatDataTime": 0
        },
        {
            "uavSellByUser": "4",
            "uavMaxspeed": 4,
            "uavProductByUser": "4",
            "playUrl1": "www.efuav.ltd/live/10055-stream1?txSecret=4ebc307e9718ef33afec1e130bf77151&txTime=655f10b4",
            "uavProductDate": 1686585600000,
            "uavDefaultHiveId": null,
            "efFactory": null,
            "uavSellDate": 1686671999000,
            "uavTypeId": 1022,
            "streamType": "webrtc",
            "efUavType": null,
            "uavStatus": 0,
            "uavName": "管理测试无人机05",
            "limitOfCompany": 0,
            "online": false,
            "uavId": "10055",
            "uavFactoryId": 4,
            "limitOfUser": 0,
            "uavContractNo": null,
            "uavEnduranceTime": 4,
            "uavMaxpayload": 4,
            "uavWheelbase": 4,
            "selected": false,
            "isOnline": false,
            "isCharging": false,
            "isChargingText": "未知",
            "isDjiServerOnline": false,
            "isGcsOnline": false,
            "isUavOnline": false,
            "isRomoteControlOnline": false,
            "isAirLinkOnline": false,
            "isCameraOnline": false,
            "djiServerBootTime": 0,
            "djiServerTime": 0,
            "heartbeatData": null,
            "heartbeatDataTime": 0
        },
        {
            "uavSellByUser": "1",
            "uavMaxspeed": 1,
            "uavProductByUser": "1",
            "playUrl1": "www.efuav.ltd/live/101004-stream1?txSecret=58a58f4ef5baf61d2a705ab032a0cee6&txTime=655f10b4",
            "uavProductDate": 1686672000000,
            "uavDefaultHiveId": "101002",
            "efFactory": null,
            "uavSellDate": 1686758399000,
            "uavTypeId": 1012,
            "streamType": "webrtc",
            "efUavType": null,
            "uavStatus": 0,
            "uavName": "管理测试无人机11",
            "limitOfCompany": 0,
            "online": false,
            "uavId": "101004",
            "uavFactoryId": 1,
            "limitOfUser": 0,
            "uavContractNo": null,
            "uavEnduranceTime": 1,
            "uavMaxpayload": 1,
            "uavWheelbase": 1,
            "selected": false,
            "isOnline": false,
            "isCharging": false,
            "isChargingText": "未知",
            "isDjiServerOnline": false,
            "isGcsOnline": false,
            "isUavOnline": false,
            "isRomoteControlOnline": false,
            "isAirLinkOnline": false,
            "isCameraOnline": false,
            "djiServerBootTime": 0,
            "djiServerTime": 0,
            "heartbeatData": null,
            "heartbeatDataTime": 0
        },
        {
            "uavSellByUser": "1",
            "uavMaxspeed": 1,
            "uavProductByUser": "1",
            "playUrl1": "www.efuav.ltd/live/101012-stream1?txSecret=61c3e4da96c459e1eb0118958aa81c25&txTime=655f10b4",
            "uavProductDate": 1686672000000,
            "uavDefaultHiveId": null,
            "efFactory": null,
            "uavSellDate": 1686758399000,
            "uavTypeId": 1012,
            "streamType": "webrtc",
            "efUavType": null,
            "uavStatus": 0,
            "uavName": "管理测试无人机22",
            "limitOfCompany": 0,
            "online": false,
            "uavId": "101012",
            "uavFactoryId": 1,
            "limitOfUser": 0,
            "uavContractNo": null,
            "uavEnduranceTime": 1,
            "uavMaxpayload": 1,
            "uavWheelbase": 1,
            "selected": false,
            "isOnline": false,
            "isCharging": false,
            "isChargingText": "未知",
            "isDjiServerOnline": false,
            "isGcsOnline": false,
            "isUavOnline": false,
            "isRomoteControlOnline": false,
            "isAirLinkOnline": false,
            "isCameraOnline": false,
            "djiServerBootTime": 0,
            "djiServerTime": 0,
            "heartbeatData": null,
            "heartbeatDataTime": 0
        },
        {
            "uavSellByUser": "1",
            "uavMaxspeed": 1,
            "uavProductByUser": "1",
            "playUrl1": "www.efuav.ltd/live/1ZBNJ5F00C008L-stream1?txSecret=4ba662cb9148d2e086ab1fd7720e4b02&txTime=655f10b4",
            "uavProductDate": 1690992000000,
            "uavDefaultHiveId": null,
            "efFactory": null,
            "uavSellDate": 1691078399000,
            "uavTypeId": 1012,
            "streamType": "webrtc",
            "efUavType": null,
            "uavStatus": -1,
            "uavName": "M300-RTK",
            "limitOfCompany": 0,
            "online": false,
            "uavId": "1ZBNJ5F00C008L",
            "uavFactoryId": 1,
            "limitOfUser": 0,
            "uavContractNo": null,
            "uavEnduranceTime": 1,
            "uavMaxpayload": 1,
            "uavWheelbase": 1,
            "selected": false,
            "isOnline": false,
            "isCharging": false,
            "isChargingText": "未知",
            "isDjiServerOnline": false,
            "isGcsOnline": false,
            "isUavOnline": false,
            "isRomoteControlOnline": false,
            "isAirLinkOnline": false,
            "isCameraOnline": false,
            "djiServerBootTime": 0,
            "djiServerTime": 0,
            "heartbeatData": null,
            "heartbeatDataTime": 0
        },
        {
            "uavSellByUser": "2",
            "uavMaxspeed": 2,
            "uavProductByUser": "2",
            "playUrl1": "www.efuav.ltd/live/456322-stream1?txSecret=2451666f4f73fe44c6bf2cf7dd256626&txTime=655f10b4",
            "uavProductDate": 1686499200000,
            "uavDefaultHiveId": "101002",
            "efFactory": null,
            "uavSellDate": 1686585599000,
            "uavTypeId": 1,
            "streamType": "webrtc",
            "efUavType": null,
            "uavStatus": 0,
            "uavName": "222",
            "limitOfCompany": 0,
            "online": false,
            "uavId": "456322",
            "uavFactoryId": 2,
            "limitOfUser": 0,
            "uavContractNo": null,
            "uavEnduranceTime": 2,
            "uavMaxpayload": 2,
            "uavWheelbase": 22,
            "selected": false,
            "isOnline": false,
            "isCharging": false,
            "isChargingText": "未知",
            "isDjiServerOnline": false,
            "isGcsOnline": false,
            "isUavOnline": false,
            "isRomoteControlOnline": false,
            "isAirLinkOnline": false,
            "isCameraOnline": false,
            "djiServerBootTime": 0,
            "djiServerTime": 0,
            "heartbeatData": null,
            "heartbeatDataTime": 0
        }
    ];
    }
  
    method1() {
      console.log('This is method 1');
    }
  
    method2() {
      console.log('This is method 2');
    }
  }
  
  export default MyModule;